{% set name = "dvc-data" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf5bfe61f68719e33f0f15470d32c7947c90ba4ab4ea5bd3dbdfec8ac379bf6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - funcy >=1.14
    - dictdiffer >=0.8.1
    - pygtrie >=2.3.2
    - shortuuid >=0.5.0
    - dvc-objects ==0.6.0
    - nanotime >=0.5.2
    - diskcache >=5.2.1
    - attrs >=21.3.0

test:
  imports:
    - dvc_data
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-data
  summary: DVC data management library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
